# Generated by Django 4.1.1 on 2022-10-10 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_liked_posts', to='post.post'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_saved_posts', to='post.post'),
        ),
    ]
